const page = () => {
  return (
    <div className="pt-[25vh] ">
      <p className="text-5xl text-center font-extrabold text-[#112D4E]">
        DISCLAIMER
      </p>
      <div className="mx-4">
        <p>
          <span className="text-2xl font-bold">Trading Risks </span> Trading in
          financial markets involves inherent risks and may result in financial
          losses. Past performance is not indicative of future results. - The
          Company&apos;s services, including algorithmic trading, are not risk-free. We
          encourage all users to trade responsibly and employ risk management
          strategies. - The Company shall not be held responsible for any losses
          incurred by users in connection with our services. Trading decisions are
          the sole responsibility of the user.
        </p>
        <br />
        <br />
        <p>
          <span className="text-2xl font-bold">Data Accuracy </span> While we
          strive to provide accurate and up-to-date data, the financial markets
          are dynamic and subject to rapid changes. The Company cannot guarantee
          the accuracy, completeness, or timeliness of data or information
          provided.
        </p>
        <br />
        <br />
        <p>
          <span className="text-2xl font-bold">Investment Advice </span> The
          information, data, and analysis provided by the Company are for
          informational purposes only and should not be considered as investment
          advice. - Users should consult with a qualified financial advisor or
          conduct their research before making any investment decisions.
        </p>
        <br />
        <br />
        <p>
          <span className="text-2xl font-bold">Algorithmic Trading </span>
          Algorithmic trading involves the use of automated trading strategies.
          While the Company provides algorithm customization tools, users are
          responsible for setting up and managing their algorithms. - The Company
          is not responsible for the performance or results of user-generated
          algorithms. Users should thoroughly test and validate their strategies
          before implementation.
        </p>
        <br />
        <br />
        <p>
          <span className="text-2xl font-bold">Technical Issues </span>The Company
          strives to maintain the availability and functionality of its services.
          However, technical issues, outages, and disruptions may occur. - The
          Company shall not be held liable for any losses or damages resulting
          from technical issues beyond our control.
        </p>
        <br />
        <br />
        <p>
          <span className="text-2xl font-bold">Privacy and Data Security </span>{" "}
          The Company values user privacy and employs industry-standard security
          measures to protect user data. Users are responsible for safeguarding
          their login credentials and personal information. - The Company&apos;s
          Privacy Policy outlines the collection, use, and protection of user
          data.
        </p>
        <br />
        <br />
        <p>
          <span className="text-2xl font-bold">Legal Compliance </span> Users are
          responsible for complying with all relevant financial regulations,
          including taxation and reporting requirements, in their respective
          jurisdictions.
        </p>
        <br />
        <br />
        <p>
          <span className="text-2xl font-bold">Amendments to Disclaimers </span>{" "}
          The Company reserves the right to modify and update these disclaimers as
          needed. Users should review the disclaimers regularly to stay informed.
        </p>
        <br />
        <br />
        <p>
          All subscription fees paid to Reliable Technologiess is Non refundable.
          We do not provide trading tips nor we are investment adviser. Our
          service is solely restricted to automated trading application
          development, deployment and maintenance. All algorithms are based on
          backtested data but we do not provide any guarantee for their
          performance in future. The algorithm running in an automated system is
          agreed with the user prior deployment and we do not take any liability
          for any loss generated by the same. Past performance of
          advise/strategy/model does not indicate the future performance of any
          current or future strategy/model or advise by Reliable Technologiess
          Trades and actual returns may differ significantly from that depicted
          herein due to various factors including but not limited to impact costs,
          expense charged, timing of entry/exit, timing of additional
          flows/redemptions, individual client mandates, specific portfolio
          construction characteristics etc. There is no assurance or guarantee
          that the objectives of any strategy/model or advice provided by Reliable
          Technologiess Trades will be achieved. Reliable Technologiess Trades or
          any of its partner/s or principal officer/employees /owner do not
          assure/give guarantee for any return on the investment in
          strategies/models/advice given to the Investor. The value of investment
          can go up/down depending on factors & forces affecting securities
          markets. Reliable Technologiess Trades or its associates are not liable
          or responsible for any loss or shortfall arising from operations and
          affected by the market condition.
        </p>
        <br />
        <br />
        <p>
          (a) The Reliable Technologiess (https://www. reliabletechnologiess
          .com/) website / software / applications / platform / portal is
          presented for informational purposes only. Any opinions, news, research,
          analyses, prices, reports, graphs, charts, links to third party website
          / software / applications / portals, or other information contained
          herein is provided for informational purposes only and does not
          constitute investment advice or recommendations. Reliable Technologiess
          is not liable for any loss or damage, including without limitation, any
          loss of profit, any loss of capital which may arise directly or
          indirectly from the use of or reliance on any such information. (b) The
          information provided on the Reliable Technologiess website / software /
          applications / platform / portal is for personal, non-commercial use for
          others. Neither the information nor any opinion contained in the
          Reliable Technologiess website / software / applications / platform /
          portal constitutes a solicitation or offer by Reliable Technologiess or
          its affiliates and partners to buy or sell any futures, options on
          futures or securities of any kind or provide any investment advice or
          service. The information on the Reliable Technologiess website /
          software / applications / platform / portal is not intended to be used
          as the primary basis of investment decisions. The Reliable Technologiess
          website / software / applications / platform / portal does not provide
          specific investment advice to any individual viewing the content of the
          website / software / applications / portal and does not represent that
          the services described herein are suitable for any specific investor.
          (c) Trading or investing carries a high level of risk, and may not be
          suitable for all persons. Before deciding to trade or invest you should
          carefully consider your investment objectives, level of experience, and
          ability to tolerate risk. The possibility exists that you could sustain
          a loss of some or all of your initial investment and, therefore, you
          should not invest money that you cannot afford to lose. You should be
          aware of all the risks associated with trading and investing, and seek
          advice from an independent financial advisor if you have any doubts.
          Past performance is not necessarily indicative of future results. (d)
          The information provided on the Reliable Technologiess website /
          software / applications / platform / portal is not intended for
          distribution to, or use by, any person or entity in any jurisdiction or
          country where such distribution or use would be contrary to law or
          regulation or which would subject Reliable Technologiess or its
          affiliates to any registration requirement within such jurisdiction or
          country. It is the responsibility of Users of this information to
          ascertain the terms of and comply with any local law or regulation to
          which they are subject. (e) The information on the Reliable
          Technologiess website / software / applications / platform / portal,
          including any links to third party website / software / applications /
          portals and the content thereon, is not guaranteed as to accuracy,
          completeness, or timeliness, and such information is subject to change
          at any time without notice, and is provided for the sole purpose of
          education and assistance in making independent investment decisions.
          Reliable Technologiess has taken reasonable measures to ensure the
          accuracy of the information contained herein; however, Reliable
          Technologiess does not guarantee its accuracy, and is not liable for any
          loss or damage which may arise directly or indirectly from such content
          or from an inability to access such information, for any delay in or
          failure of the transmission or receipt of any instruction or
          notification in connection therewith. (f) Information contained on the
          Reliable Technologiess website / software / applications / platform /
          portal, including pricing, valuation, and commentary on specific
          products, if any, reflects the authors’ analysis and other information
          available as of the publication date indicated. Furthermore, any news,
          opinions, commentaries, opinions, data, pricing, links to third party
          website / software / applications / portals, and all other information
          contained on the Reliable Technologiess website / software /
          applications / platform / portal are believed to be reliable, but
          Reliable Technologiess cannot and does not guarantee its accuracy,
          timeliness, or completeness. Reliable Technologiess expressly disclaims
          any warranties of merchantability or fitness for a particular purpose.
          Reliable Technologiess will not be responsible for any loss or damage
          that could result from interception by third parties of any information
          transmitted electronically or otherwise in connection with this website
          / software / applications / portal. (g) Neither Reliable Technologiess ,
          nor any of its affiliates, directors, officers or employees, nor any
          third party vendor or service provider will be liable or have any
          responsibility of any kind for any loss or damage that you incur in the
          event of any failure or interruption of this website / software /
          applications / portal, or resulting from the act or omission of any
          other party involved in making this website / software / applications /
          portal, or the website / software / applications / portal’s data,
          available to you, or from any other cause relating to your access to,
          inability to access, or use of the website / software / applications /
          portal or these materials, whether or not the circumstances giving rise
          to such cause may have been within the control of Reliable Technologiess
          or of any vendor providing software or services support. (h)
          Hypothetical trading results may appear on the Reliable Technologiess
          website / software / applications / platform / portal. (i) Hypothetical
          performance results have many inherent limitations, some of which are
          described below. no representation is being made that any account will
          or is likely to achieve profits or losses similar to those shown; in
          fact, there are frequently sharp differences between hypothetical
          performance results and the actual results subsequently achieved by any
          particular trading program. One of the limitations of hypothetical
          performance results is that they are generally prepared with the benefit
          of hindsight. In addition, hypothetical trading does not involve
          financial risk, and no hypothetical trading record can completely
          account for the impact of financial risk of actual trading. For example,
          the ability to withstand losses or to adhere to a particular trading
          program in spite of trading losses are material points which can also
          adversely affect actual trading results. There are numerous other
          factors related to the markets in general or to the implementation of
          any specific trading program which cannot be fully accounted for in the
          preparation of hypothetical performance results and all of which can
          adversely affect trading results.
        </p>
        <br />
        <br />
        <p className="text-2xl font-bold">
          Third Party Website / Software / Applications / Platform / Portals And
          Services
        </p>
        <p>
          (a) The Reliable Technologiess website / software / applications/
          platform / portal may contain links to third party website / software /
          applications/ platform / portals, which are owned and operated by
          unaffiliated third parties, and may contain offers for various products,
          services, or information (collectively referred to as “Third Party
          Services”). Reliable Technologiess is not responsible for the contents
          of any such linked sites and does not assume any responsibility for the
          accuracy or appropriateness of the information contained on such sites.
          The inclusion of any link does not imply endorsement by Reliable
          Technologiess. No claims are made as to the reliability of past, present
          or future profitability in connection with the use of any of these
          Third-Party Services. Reliable Technologiess does not guarantee that use
          of these Third-Party Services will generate or result in any profits.
          (b) User acknowledges that Third Party Services are produced and owned
          by third parties, and not Reliable Technologiess, and that Reliable
          Technologiess disclaims any responsibility for any Third-Party Services
          provided to User. User is responsible for conducting his or her own due
          diligence with respect to any Third-Party Service utilized by User. User
          assumes all risk/liability for such Third-Party Service. (c) Reliable
          Technologiess makes no representations or warranties whatsoever,
          expressed or implied, as to the accuracy, completeness, timeliness,
          appropriateness, suitability or fitness for any purpose or use of such
          Third-Party Services, products, services and information, customer and
          technical support or web presence or any of their presentations or
          representations. User acknowledges and agrees that Reliable
          Technologiess shall not be liable in any way for the use of such
          Third-Party Services. (d) User acknowledges and agrees that this
          Agreement Grants User no rights or licenses with respect to any
          Third-Party Service, and User agrees that use of any Third-Party
          Services shall be in accordance with any agreements or other governing
          rules applicable to such Third-Party Services. User acknowledges and
          agrees that Reliable Technologiess has no obligation to maintain or
          provide any updates to User regarding any changes to agreements related
          to Third Party Services. User is responsible for reading and
          understanding the terms and conditions and any other policies of any
          Third-Party Services utilized by User. Any questions related to such
          Third-Party Services should be directed to the third party providing the
          service.
        </p>
        <br />
        <br />
        <p className="text-2xl font-bold">User Subscription Fees And Service Renewals</p>
        <p>
          (a) All User subscriptions for the Service provided by Reliable
          Technologiess will not automatically renew. Users must submit renewal
          requests by email to info@reliabletechnologiess.com at least 48 hours
          prior to the renewal date in order to not face any discontinuity in the
          service. Upon termination of the Service, User acknowledges that all
          monthly subscription fees previously paid by User’s credit card / debit
          card / UPI / net banking in consideration for User’s access to the
          Service will not be refunded, in whole or in part (b) All sales are
          final and subscription fees are non-refundable. Reliable Technologiess ,
          in its sole discretion, however, reserves the right to refund all or
          part of User’s subscription fees. User agrees to pay any fees that may
          be assessed in connection with any products, Services, subscriptions, or
          information ordered by User, as well as any related taxes. User also
          agrees to pay all costs (including attorneys’ fees and expenses)
          incurred by Reliable Technologiess in collecting any unpaid or overdue
          fees. (c) User represents and warrants to be the owner, holder and
          authorized user of the credit card / debit card / UPI / net banking
          identified in the Reliable Technologiess registration form.
        </p>
        <br />
        <br />
        <p className="text-2xl font-bold">Waiver Of Liability</p>
        <p>
          User agrees that access to and use of the information contained in the
          Reliable Technologiess website / software / applications / platform /
          portal is at the User&apos;s risk, and User agrees that no claim shall be
          alleged or asserted against Reliable Technologiess or anyone affiliated
          therewith based on any allegation or contention that any of the
          information was deficient or inaccurate. In addition, any reference to
          any Third-Party Service at or on the Reliable Technologiess website /
          software / applications / platform / portal or any linked site is not an
          express or implied endorsement by limitation Reliable Technologiess .
          All the information, software, content, products and services available
          from Reliable Technologiess are provided on an &quot;as-is&quot; and &quot;as-
          available&quot; basis, with no warranties of any kind. Reliable Technologiess
          expressly disclaims any and all warranties, express or implied,
          including without the warranty of merchantability, fitness for a
          particular purpose, and noninfringement. Reliable Technologiess
          disclaims any warranty that the site will always be accessible or
          operational, that the information provided at the site is accurate,
          reliable or correct, and that any errors will be corrected. You agree
          that, under no circumstances and to the fullest extent allowed by
          applicable law, will Reliable Technologiess be liable for any and all
          damages under any and all theories (including contract, negligence,
          strict liability or tort) arising out of or relating in any way to this
          agreement, the content, including without limitation any Reliable
          Technologiess content or third party content, the site, your use or
          inability to use the site, or any decision or action you make in
          connection with the site. You agree that, under no circumstances and to
          the fullest extent allowed by applicable law, the maximum aggregate
          liability, if any, that Reliable Technologiess may owe to you in
          connection with this agreement, the site, and your use of the site and
          its content, shall not, under any circumstance or theory of law or
          recovery, exceed Rs 1/-. your only other remedy for dissatisfaction with
          the site, site related services or content or information contained
          within the site is to stop using the site and the services offered or
          provided and to cancel any subscription. certain state laws do not allow
          limitations on implied warranties or the exclusion or limitation of
          certain damages. If these laws apply to you, some or all of the above
          disclaimers, exclusions, or limitations may not apply to you, and you
          might have additional rights but the arbitrator shall always be
          appointed by Reliable Technologiess firm.
        </p>
        <br />
        <br />
        <p className="text-2xl font-bold">Termination of agreement</p>
        <p>
          (a) Reliable Technologiess may terminate this Agreement and User’s
          access the Service at any time and for any reason upon notice to User.
          In general, however, Reliable Technologiess will consider terminating
          this Agreement if (i) User fails to observe any provision of this
          Agreement; (ii) after the payment of subscription fees if the users
          request to cancel the service. Upon cancellation, User will be denied
          further access to the Service provided by Reliable Technologiess , and
          Reliable Technologiess will have no obligation to return any portion of
          the subscription fees remitted by User paid prior to cancellation of the
          Service by either Reliable Technologiess or User. (b) Reliable
          Technologiess may discontinue the Service, at any time and for any
          reason upon notice to User.
        </p>
        <br />
        <br />
        <p className="text-2xl font-bold">Limited User License</p>
        <p>
          (a) All content provided by Reliable Technologiess on the Service is
          protected by copyright, trademark, and other applicable intellectual
          property and proprietary rights laws and is owned, controlled, and/or
          licensed by Reliable Technologiess. The Service is protected by
          copyright, patent, trademark, and other applicable intellectual property
          and proprietary rights laws and is owned, controlled, and/or licensed by
          Reliable Technologiess. All trademarks appearing on the Service are the
          property of their respective owners. (b) Content provided by the Service
          may be searched, retrieved, displayed, downloaded, and printed by Users
          for personal use only. Users shall make no other use of such content
          without the express written permission of Reliable Technologiess. Users
          shall not modify any of the content provided by the Service, and in
          particular Users shall not delete or alter any proprietary rights or
          attribution notices in any content. User acknowledges and agrees that no
          ownership rights are acquired by User in connection with his or her use
          of the Service. User further acknowledges and agrees that all rights not
          granted to User under this Agreement are expressly reserved by Reliable
          Technologiess and/or its licensors. (c) No User is allowed to copy,
          sell, license, modify, distribute, reproduce, transmit, publicly
          display, publicly perform, publish, adapt or edit any of the materials
          or content appearing on Reliable Technologiess’ website / software /
          applications / portal, in whole or in part, except as expressly
          authorized by this Agreement. (d) This Agreement and limited license is
          granted solely to User, and may not be assigned or transferred by User.
          User acknowledges and agrees that User is strictly prohibited from
          allowing third parties to access the Reliable Technologiess website /
          software / applications / platform / portal or Services. User
          acknowledges and agrees that User is solely responsible for any
          liability arising from any third-party access to or use of the Reliable
          Technologiess website / software / applications / platform / portal
          permitted or facilitated by User, whether negligently or otherwise
        </p>
        <br />
        <br />
        <p className="text-2xl font-bold">Indemnification</p>
        <p>
          User agrees to indemnify, defend and hold harmless Reliable
          Technologiess, its officers, directors,owners, employees, agents,
          information providers and suppliers from and against all claims, causes
          of action, suits, losses, expenses, damages and costs, including
          reasonable attorney’s fees, arising out of, in connection with or
          relating to any violation by you of this Agreement, including claims of
          infringement of intellectual property or other third party rights, or
          otherwise, directly or indirectly resulting from or attributable in any
          way to any access to, use of or posting of material or content on the
          Reliable Technologiess website / software/applications/platform/ portal
          by you.
        </p>
        <br />
        <br />
        <p className="text-2xl font-bold">Access And Interference</p>
        <p>
          (a) User agrees to use the Service and any content, material, or
          information associated therewith solely for lawful purposes. User shall
          not upload to, distribute, or otherwise disseminate through the Service
          any material or information of any kind that is libellous-, defamatory,
          obscene, pornographic, abusive, or otherwise violates any law or
          infringes or violates any rights of any other person or entity, or
          contains a solicitation of funds, advertising, or a solicitation for
          goods or services. (b) User agrees to not use any robot, spider, other
          automatic device, or manual process to monitor or copy any of Reliable
          Technologiess’ web pages, or the content contained thereon, or for any
          other unauthorized purpose without Reliable Technologiess’ prior express
          written permission. User agrees to not use any device, software, or
          routine to interfere or attempt to interfere with the proper functioning
          of the Reliable Technologiess website / software / applications /
          platform / portal. User agrees to not take any action that imposes an
          unreasonable or disproportionately large load on the Reliable
          Technologiess infrastructure and User agrees not to engage in any
          unauthorized framing, linking, or deep-linking to the Reliable
          Technologiess website / software / applications / platform / portal
          without the prior written consent of Reliable Technologiess.
        </p>
        <br />
        <br />
        <p className="text-2xl font-bold">Statement Of Privacy</p>
        <p>
          (a)Reliable Technologiess is committed to protecting your privacy and
          maintaining the confidentiality and security of your information. In
          accordance with its legal obligations, Reliable Technologiess is
          required to inform you how it treats certain information concerning
          Users and how such information is used to service Users. Please refer to
          Reliable Technologiess’ Privacy Policy found on its website / software /
          applications / portal for additional information pertaining to the use
          of information. (b) Reliable Technologiess reserves the right to collect
          and use data about Users and use of the Service for its own internal
          purposes, e.g., performing statistical analyses to assist Reliable
          Technologiess in improving the Service. Reliable Technologiess further
          reserves the right to distribute such data in formats that do not
          identify individual Users. Reliable Technologiess may distribute data in
          formats identifying without User’s prior written consent to such
          distribution of information.
        </p>
        <br />
        <br />
        <p className="text-2xl font-bold">Notices</p>
        <p>
          User may contact Reliable Technologiess by sending an email to the
          following email address: info@reliabletechnologiess.com Reliable
          Technologiess will contact User by sending an email to the email address
          provided by User.
        </p>
        <br />
        <br />
        <p className="text-2xl font-bold">No Assignment</p>
        <p>
          The rights and obligations associated with this Agreement and limited
          license belong only to the User, and may not be assigned or sold to or
          used by another person or entity without the prior written consent of
          Reliable Technologiess. User acknowledges and agrees that User is
          strictly prohibited from allowing third parties to access the Reliable
          Technologiess website/software/applications/platform <br /> /portal or Services
          without the prior written consent of Reliable Technologiess. User
          acknowledges and agrees that User is solely responsible for any
          liability arising from any third party access to or use of the Reliable
          Technologiess website / software / applications / platform / portal
          permitted or facilitated by User, whether negligently or otherwise.
        </p>
        <br />
        <br />
        <p className="text-2xl font-bold">Other Terms And General Provisions</p>
        <p className="mb-4">
          (a) This Agreement between User and Reliable Technologiess supersedes
          and replaces any prior agreement between User and Reliable Technologiess
          . (b) If any term or provision of this Agreement is found by a court of
          competent jurisdiction to be void, invalid, unenforceable or otherwise
          contrary to law, the remainder of the Agreement that can be given effect
          without such term or provision shall be given full effect. (c) Any
          failure by Reliable Technologiess to enforce strict performance of any
          provision of this Agreement will not constitute a waiver of its right
          subsequently to enforce such provision or any other provision of the
          Agreement. (d) No representation is being made nor implied that the use
          of algorithmic trading system will generate income or guarantee a
          profit. There is a substantial risk of loss associated with futures
          trading and algorithmic trading traded funds. (e) Futures trading and
          trading exchange traded funds involve a substantial risk of loss and is
          not appropriate for everyone. (f) These results are based on simulated
          or hypothetical performance results that have certain inherent
          limitations. Unlike the results shown in an actual performance record,
          these results do not represent actual trading. Also, because these
          trades have not actually been executed, these results may have under-or
          over-compensated for the impact, if any, of certain market factors, such
          as lack of liquidity. Simulated or hypothetical trading programs in
          general are also subject to the fact that they are designed with the
          benefit of hindsight. No representation is being made that any account
          will or is likely to achieve profits or losses similar to these being
          shown. (g) Hypothetical or simulated performance results have certain
          limitations. Unlike an actual performance record, simulated results do
          not represent actual trading. also, since the trades have not been
          executed, the results may have under-or-over compensated for the impact,
          if any, of certain market factors, such as lack of liquidity. Simulated
          trading programs in general are also subject to the fact that they are
          designed with the benefit of hindsight. No representation is being made
          that any account will or is likely to achieve profit or losses similar
          to those shown.
        </p>
      </div>
    </div>
  );
};

export default page;
